version: '3.9'
services:
  nginx:
    image: localhost/openresty-prometheus:latest
    hostname: photos.rickykwan.ca  # used in server_name
    build:
      context: nginx/docker
    container_name: nginx
    environment:
      TZ: America/Toronto
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/custom-resources:/app/custom-resources
      - "nginx-logs-shared:/app/logs"
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 127.0.0.1:8080:8080
      - 80:80
      # - 443:443  # tls handled by cloudflare
    restart: unless-stopped

  pigallery2:
    image: localhost/pigallery2:1.9.5
    build:
      context: pigallery/docker
    container_name: pigallery2
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
    volumes:
      - "db-data:/app/data/db"
      - "./_userdata/config:/app/data/config" # CHANGE ME
      - "./_userdata/images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
      - "./_userdata/tmp:/app/data/tmp" # CHANGE ME
    expose:
      - "80"
    restart: unless-stopped

volumes:
  db-data:
    name: pigallery2_db_data

  nginx-logs-shared:
    name: pigallery2_nginx_logs_shared
