version: '3.9'
services:
  nginx:
    image: localhost/openresty-prometheus:latest
    hostname: photos.rickykwan.ca  # used in server_name
    build:
      context: docker/openresty
    container_name: nginx
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./custom-resources:/app/custom-resources
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 127.0.0.1:8080:8080
      - 80:80
      # - 443:443  # tls handled by cloudflare
    restart: unless-stopped

  pigallery2:
    image: bpatrik/pigallery2:1.9.5
    container_name: pigallery2
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
    volumes:
      - "./pigallery2/config:/app/data/config" # CHANGE ME
      - "db-data:/app/data/db"
      - "./pigallery2/images:/app/data/images:ro" # CHANGE ME, ':ro' means read-only
      - "./pigallery2/tmp:/app/data/tmp" # CHANGE ME
    expose:
      - "80"
    restart: unless-stopped

volumes:
  db-data:
    name: pigallery2_db_data
