version: '3.9'

services:
  prometheus:
    image: bitnami/prometheus:2.43.0
    container_name: prometheus
    volumes:
      - "prom-data:/opt/bitnami/prometheus/data"
      - "./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"
    ports:
      - 127.0.0.1:9090:9090
      # - 9090:9090
    expose:
      - 9090
    restart: unless-stopped
    command:
      - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
      - "--storage.tsdb.retention=21d"

  promtail:
    image: bitnami/promtail:2.8.2
    container_name: promtail
    restart: unless-stopped
    volumes:
      - "./promtail/config.yml:/etc/promtail/config.yml:ro"
      - "nginx-logs-shared:/nginx-logs"
    command: "-config.file=/etc/promtail/config.yml"
    expose:
      - 9080
    depends_on:
      - loki

  loki:
    image: bitnami/grafana-loki:2.8.2
    container_name: loki
    expose:
      - 3100
    volumes:
      - "./loki/local-config.yml:/etc/loki/local-config.yaml:ro"
      - "loki-data:/bitnami/grafana-loki/loki:rw"
    command: "-config.file=/etc/loki/local-config.yaml"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - "./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/:ro"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/:ro"
      - "./grafana/dashboards/:/var/lib/grafana/dashboards/:ro"
    ports:
      - 127.0.0.1:3000:3000
      #- 3000:3000
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=N0nDEf_ault2468Pass-Word"

volumes:
  prom-data:
    name: pigallery2_prom_data

  grafana-data:
    name: pigallery2_grafana_data

  nginx-logs-shared:
    name: pigallery2_nginx_logs_shared

  loki-data:
    name: pigallery2_loki_data
