server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/tmp/promtail-syslog-positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx-access
    static_configs:
      - labels:
          job: nginxlogs
          __path__: /logs/nginx_access.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            ip: ip
            cf_connecting_ip: cf_ip
            request: request
            status: status
            duration: duration
            body_bytes: body_bytes
            referer: referer
            ua: ua
      - labels:
          status:
          cf_connecting_ip:
          referer:
      - timestamp:
          source: timestamp
          format: ISO-8601

  - job_name: nginx-error
    static_configs:
      - labels:
          job: nginxlogs
          __path__: /logs/nginx_error.log
