{
 "title": "Bootstrap: Nginx Metrics and Logs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "logs_status_filter", "label": "Logs Status", "query": "^2.*, ^3.*, ^4.*, ^5.*" },
   { "name": "location", "label": "Location", "query": { "query": "label_values(location)" } }
  ]
 },
 "panels": [
  {
   "title": "Gallery Page Loads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_gallery_page_load[120s]) * 60",
     "legendFormat": "rate nginx_gallery_page_load"
    },
    {
     "expr": "nginx_gallery_page_load",
     "legendFormat": "absolute nginx_gallery_page_load"
    }
   ]
  },
  {
   "title": "request duration (s) (${location:pipe})",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (nginx_http_request_duration_seconds_bucket{location=~\"^(${location:pipe})$\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "nginx_http_requests_total (200s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(nginx_http_requests_total{status=~\"^2[0-9]+$\", location=~\"^(${location:pipe})$\"}, \"instance\", \"\", \"instance\", \".*\"), \"host\", \"\", \"host\", \".*\"), \"job\", \"\", \"job\", \".*\"), \"__name__\", \"\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{location}} ({{status}})"
    }
   ]
  },
  {
   "title": "nginx_http_requests_total (300s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(nginx_http_requests_total{status=~\"^3[0-9]+$\", location=~\"^(${location:pipe})$\"}, \"instance\", \"\", \"instance\", \".*\"), \"host\", \"\", \"host\", \".*\"), \"job\", \"\", \"job\", \".*\"), \"__name__\", \"\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{location}} ({{status}})"
    }
   ]
  },
  {
   "title": "Gallery Image Views",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(nginx_gallery_image_view[120s]) * 60",
     "legendFormat": "rate nginx_gallery_image_view"
    },
    {
     "expr": "nginx_gallery_image_view",
     "legendFormat": "absolute nginx_gallery_image_view"
    }
   ]
  },
  {
   "title": "nginx_http_requests_total (400s, 500s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(nginx_http_requests_total{status=~\"^(4|5)[0-9]+$\", location=~\"^(${location:pipe})$\"}, \"instance\", \"\", \"instance\", \".*\"), \"host\", \"\", \"host\", \".*\"), \"job\", \"\", \"job\", \".*\"), \"__name__\", \"\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{location}} ({{status}})"
    }
   ]
  },
  {
   "title": "nginx_http_requests_total rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(\r\n    label_replace(\r\n        label_replace(\r\n            rate(nginx_http_requests_total[120s]) * 60,\r\n        \"instance\", \"\", \"instance\", \".*\"),\r\n    \"host\", \"\", \"host\", \".*\"),\r\n\"job\", \"\", \"job\", \".*\")",
     "legendFormat": "{{location}} ({{status}})"
    }
   ]
  },
  {
   "title": "nginx_http_connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(label_replace(nginx_http_connections{job=\"photos-nginx\"}, \"instance\", \"\", \"instance\", \".*\"), \"__name__\", \"\", \"__name__\", \".*\")",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Nginx Logs (status: ${logs_status_filter:pipe})",
   "type": "logs",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{component=\"nginx\", status=~\"(${logs_status_filter:pipe})\"}"
    }
   ]
  },
  {
   "title": "Status 200s Unique IPs",
   "type": "table",
   "gridPos": { "h": 14, "w": 3, "x": 21, "y": 23 },
   "targets": [
    {
     "expr": "{component=\"nginx\", cf_connecting_ip != \"\", status=~\"^2.*\"}"
    }
   ]
  }
 ]
}